### ISSUE TITLE
Demo app is unable to answer calls.

### ISSUE THREAD

**Issue by binhly** [signalwire/signalwire-node#246]
After successfully setting up the react-native project to run in the iOS simulator I am able to create outbound calls.

But upon receiving inbound calls I get the following error message:

Any tips on how to go about debugging this?  I'm now to WebRTC.

![Simulator Screen Shot - iPhone 11 - 2020-04-05 at 13 18 16](https://user-images.githubusercontent.com/8120153/78509062-2cb6a100-7740-11ea-81f6-2bc5a29e4533.png)

**Comment by edolix** [comment]
Hi @binhly , i'd suggest to test the application or a real device because WebRTC requires to access microphone/camera that iOS simulator doesn't support.
I've build right now the demo app for both Android and iOS and seems to work fine.

Can you give me some more info on what you're doing, please?

Also, make sure to run the latest version of [@signalwire/react-native](https://www.npmjs.com/package/@signalwire/react-native).
Thanks!

**Comment by edolix** [comment]
Hi @binhly, i'm going to close this issue. Feel free to reopen or comment here for any other questions.

Thanks!
